apiVersion: firewall.opnsense.io/v1alpha1
kind: OPNsenseConnection
metadata:
  labels:
    app.kubernetes.io/name: opnsense-operator
    app.kubernetes.io/managed-by: kustomize
  name: default
spec:
  url: https://192.168.56.101
  credentials:
    secretRef:
      name: opnsense-api-credentials
      namespace: opnsense-operator-system
  tls:
    insecureSkipVerify: true   # dev only — disables TLS certificate verification
  # tls:
  #   caSecretRef:             # production — custom CA bundle
  #     name: opnsense-ca
  #     namespace: opnsense-operator-system
